### ISSUE TITLE
Failed to get mouflon decryption key

### ISSUE THREAD

**Issue by CaptainPornHelper** [lossless1024/StreaMonitor#270]
I keep getting this error and I'm not sure if I'm supposed to input this manually or what I'm doing wrong exactly.

```
add Performer StripChat
2025-12-01 21:20:32,310 - INFO - manager_cli: Added [SC] Performer
> 2025-12-01 21:20:33,806 - ERROR - [SC] Performer: Response ended prematurely
Traceback (most recent call last):
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/urllib3/response.py", line 1088, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/urllib3/response.py", line 1248, in read_chunked
    self._update_chunk_length()
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/urllib3/response.py", line 1178, in _update_chunk_length
    raise ProtocolError("Response ended prematurely") from None
urllib3.exceptions.ProtocolError: Response ended prematurely

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Downloads/cams/StreaMonitor/streamonitor/bot.py", line 166, in run
    self.sc = self.getStatus()
              ^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/cams/StreaMonitor/streamonitor/sites/stripchat.py", line 162, in getStatus
    r = self.session.get(
        ^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Downloads/cams/lib/python3.11/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: Response ended prematurely
2025-12-01 21:20:33,810 - INFO - [SC] Performer: Not running
2025-12-01 21:20:54,485 - INFO - [SC] Performer: Channel online
2025-12-01 21:20:55,097 - INFO - [SC] Performer: Failed to get mouflon decryption key
2025-12-01 21:20:55,098 - ERROR - [SC] Performer: No available sources
2025-12-01 21:20:55,098 - ERROR - [SC] Performer: Error on downloading
```
Thanks in advance.

**Comment by medi0x1** [comment]
Your issue is fixed in PR #268. Try using that version.
Download the updated stripchat.py nd replace yours. Should fix the mouflon key error!

**Comment by CptChaos** [comment]
> Your issue is fixed in PR [#268](https://github.com/lossless1024/StreaMonitor/pull/268). Try using that version. Download the updated stripchat.py nd replace yours. Should fix the mouflon key error!

What do people running the Docker container need to do? I have the latest image already, but somehow still get the error.

**Comment by elphabert** [comment]
@CptChaos  Main has been updated with the changes and it appears docker has been pushed since then so you should have this JSON present https://github.com/lossless1024/StreaMonitor/blob/master/stripchat_mouflon_keys.json, modify it to include the decryption key from the top of stripchat.py in Medi's PR

**Comment by CptChaos** [comment]
> [@CptChaos](https://github.com/CptChaos) Main has been updated with the changes and it appears docker has been pushed since then so you should have this JSON present https://github.com/lossless1024/StreaMonitor/blob/master/stripchat_mouflon_keys.json, modify it to include the decryption key from the top of stripchat.py in Medi's PR

@elphabert What is the use in that? Most files are inside the container, it would only be temporary, as changes will be reverted when the image has restarted?

**Comment by TecnoBlast** [comment]
> [@elphabert](https://github.com/elphabert) What is the use in that? Most files are inside the container, it would only be temporary, as changes will be reverted when the image has restarted?

find the .json path and bind it as a local file, so won't be replaced at restarts but mirrors content of yours

**Comment by CptChaos** [comment]
> find the .json path and bind it as a local file, so won't be replaced at restarts but mirrors content of yours

@TecnoBlast As far as I can see, the mouflon json should be in the same directory as stripchat.py so I made a volume mount to it now (my container didn't have the file at all yet), but how do I find the keys and values that need to go in it? Sorry, I don't understand Python very well.
